// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPI3pHpuGh1j5OSpskUGyxUyQp5rr7A5c',
    appId: '1:926269013167:web:449260e7ff64b2279fa85a',
    messagingSenderId: '926269013167',
    projectId: 'reside-ease-ac363',
    authDomain: 'reside-ease-ac363.firebaseapp.com',
    storageBucket: 'reside-ease-ac363.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0hgvo1JsLBWE7WljOWR-te5wMgHUiGs',
    appId: '1:926269013167:android:016fb7e58de073e39fa85a',
    messagingSenderId: '926269013167',
    projectId: 'reside-ease-ac363',
    storageBucket: 'reside-ease-ac363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-Q6WRdYMzfT31SEYi4SxEbjmtc7bKUM',
    appId: '1:926269013167:ios:5efcea8310f3677a9fa85a',
    messagingSenderId: '926269013167',
    projectId: 'reside-ease-ac363',
    storageBucket: 'reside-ease-ac363.appspot.com',
    iosClientId: '926269013167-r7vp2nmegmt6nm4mp5t267kn0v92rn47.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-Q6WRdYMzfT31SEYi4SxEbjmtc7bKUM',
    appId: '1:926269013167:ios:d8be0e523ccbac449fa85a',
    messagingSenderId: '926269013167',
    projectId: 'reside-ease-ac363',
    storageBucket: 'reside-ease-ac363.appspot.com',
    iosClientId: '926269013167-5rgts96rvkggnlue1ai65d0bko5v6k6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
